### ISSUE TITLE
Generation Time Limit 

### ISSUE THREAD

**Issue by abhigoku10** [johnGettings/LIHQ#4]
@johnGettings Hi thanks for sharing this wonderful code base had a few queries which have been listed below 
1. The whole pipeline can be used to generate videos of about <1 min. cant we extend to more than 1 min? is so what is the constraint which we can face 
2. Instead of using text 2 audio can we pass in the direct audio file to the module then one process shall be reduced right 

Thanks in advance

**Comment by johnGettings** [comment]
1) Honestly I haven't used this repo in a while but from what I remember I think you can use whatever audio length you want. I'm pretty sure the architecture allows for any length of audio without an increase in VRAM over time. Where are you seeing this one minute limit? Maybe I said somewhere that I recommend projects under one minute due to the massive amount of inference time. 

2) You absolutely can use your own audio. Just add a subfolder under the default '/content/LIHQ/input/audio' folder and drop your audio there. You can completely skip the text to speech portion if you like.
